### ISSUE TITLE
[BUG] Selected the wrong saber

### ISSUE THREAD

**Issue by blackorbit1** [ToniMacaroni/SaberFactory#129]
Hello 👋 
I've got a strange bug few days ago where I selected the plasma katana and it applied another one : 
<div align="left">
      <a href="https://www.youtube.com/watch?v=RXmrc3rfLlA">
         <img src="https://img.youtube.com/vi/RXmrc3rfLlA/0.jpg" style="width:100%;">
      </a>
</div>
Note: I think I've never used the saber it applied so it's not like it came back to the previous saber or it didn't replace the one I just used
<br><br>
Here is the normal behavior : 
<div align="left">
      <a href="https://www.youtube.com/watch?v=QV6B6h1BGm8">
         <img src="https://img.youtube.com/vi/QV6B6h1BGm8/0.jpg" style="width:100%;">
      </a>
</div>

I know the ticket is really poor in information but maybe it could help to see patterns if there is multiple reports about this issue

**Comment by ToniMacaroni** [comment]
The current UI implementation has a bug where it's sometimes still interactable during the animation. So when clicking something fast after dismissing the SF UI it would still select something in SF. Looking at the first clip it seems that this is what happened.
SF3 is currently in development which has a new UI implementation and I haven't noticed this bug in that version.

**Comment by blackorbit1** [comment]
Oh I see. Thank you for response ! 
I closed the issue 👍
