### ISSUE TITLE
[BUG] Global vars _UserColorLeft and _UserColorRight not updating.

### ISSUE THREAD

**Issue by AlexxSeven** [ToniMacaroni/SaberFactory#136]
The two SF global variables for grabbing saber color scheme are not being updated as `SetupGlobalShaderVars();` is only called during initialization.

This results in only grabbing the color scheme once during game load rather than dynamically.

**Comment by ToniMacaroni** [comment]
That is true v2 only updates the colors during init.
Though I think I already fixed it in v3 as I also changed the architecture of it a quite a bit.
I will probably still merge the PR after a review as long as v3 isn't out yet.

**Comment by AlexxSeven** [comment]
Yeah I forget where I read that you were already working on v3 of saber factory so i didn't bother to press on this or the other bug reports either.

the PR is a smol change that still uses your original code for setting those variables, just relocates the function so that the saber instance class handles it, that way they can chance color at will without any worry since on map play its called to set up the sabers lol.

Looking forward to V3!
