### ISSUE TITLE
Antivirus marking as untrustworthy

### ISSUE THREAD

**Issue by MrPickles2009** [ToniMacaroni/SaberFactory#17]
My antivirus is flagging your mod as untrustworthy. Any idea why this might be?
Are you signing your builds?

**Comment by mhombach** [comment]
@MrPickles2009 If it's just "untrustworthy" I guess that's ok. I would be more concerned if it flags the dll as malicious, because that would mean that we should change something so that flagging disappears (because it's not malicious ofc :) ).
