### ISSUE TITLE
trails are a bit funky

### ISSUE THREAD

**Issue by zivoy** [ToniMacaroni/SaberFactory#18]
on all the sabers iv;e tested but mainly on [dot spiral v1](https://modelsaber.com/Sabers/?id=1575828486&pc) the saber trail is in the middle of the saber and upside down
![upside down and in center](https://cdn.discordapp.com/attachments/739380641216593961/807687804166340658/unknown.png)
it was sort if fine in [v2.0.1](https://github.com/ToniMacaroni/SaberFactoryV2/releases/tag/2.0.1) but broke when I updated to the latest version
in v2.0.1 it was still upside down but at least it was at the tip of the saber 
![tip](https://cdn.discordapp.com/attachments/739373520164880525/807691075866067004/unknown.png)

**Comment by ToniMacaroni** [comment]
Fixed in #19
