### ISSUE TITLE
Why no saber builder?

### ISSUE THREAD

**Issue by DanHolli** [ToniMacaroni/SaberFactory#26]
I could build my own saber complete with custom trails, why can I not do it with this version?

**Comment by ghost** [comment]
Currently Saber Factory V2 doesn't support full saber customization. Toni is still working on implementing that.
If you still want full saber customization however, you can download Saber Factory v1.6.3 as it still works with the latest version of Beat Saber: https://github.com/ToniMacaroni/SaberFactory/releases
