### ISSUE TITLE
Saber Trails are gone after pausing

### ISSUE THREAD

**Issue by SteffoSpieler** [ToniMacaroni/SaberFactory#34]
I can't show any log as I have another problem with SaberFactory (#33) - but I can show the issue in a video:

https://user-images.githubusercontent.com/41108856/113141764-66729880-922a-11eb-87c0-bf868c5f28e7.mp4

Just ask if you need more information.

**Comment by ToniMacaroni** [comment]
Fixed in newest update
#35
