### ISSUE TITLE
Sabers turn into rockets

### ISSUE THREAD

**Issue by MusicalPilot** [ToniMacaroni/SaberFactory#37]
I don't know if this is related to the yeeting trails issue, but this certainly does not only happen during replays as that issue does. My problem is that every other song I play (or song attempt), my sabers will shoot themselves entirely into the game map with what looks to be rocket jets off the end of them. I have no trick saber mods installed (and never have), it only happens every other song play, it doesn't matter what saber or setting I use in SaberFactory, and and it just started happening randomly out of nowhere. I was in a Beat Saber session for over an hour without issues, put the headset down to get water, then started again without closing anything and the issue started happening. This is one of two issues that randomly started happening at the same time (see SongCore issue below), and I have already tried uninstalling and reinstalling literally everything but the issue continues. SaberFactory is up to date as shown in ModAssistant (v2.2.2). Disabling/uninstalling SaberFactory is the only thing that prevents this issue. 

SongCore issue: https://github.com/Kylemc1413/SongCore/issues/55 

Video demonstration: https://youtu.be/O79r0Ups2sQ

**Comment by HappyNows** [comment]
srsly, this is happening to me as well under the exact same circumstances and the exact same way, I tried updating it to the github one too...

**Comment by SteffoSpieler** [comment]
Same Issue..

https://user-images.githubusercontent.com/41108856/113294226-03026c80-92f7-11eb-8f64-49fc178cf727.mp4

**Comment by SteffoSpieler** [comment]
Maybe it's a april fool?

**Comment by HappyNows** [comment]
maybe, going to just downgrade versions till tomorrow lol

**Comment by stexm** [comment]
Same issue here, really frustrating. that's one nasty April fool's.

**Comment by samuel-flynn** [comment]
I, for one, thought it was hilarious. I was so confused the first time it happened to me. Combine it with Custom Notes for an even better experience.

Well played, devs. Well played. 👏

**Comment by Ultra-Meloncrafter** [comment]
but the sabers are usable so you dont need to downgrade it because the models are away but the hitboxes are still there

**Comment by ToniMacaroni** [comment]
Yeah this was an april fool.
Tho it was meant to happen only once on the first song,
but the switch kept reverting on every second play.
Fixed the issue now.
