### ISSUE TITLE
Spamming critical errors because trail value is 0

### ISSUE THREAD

**Issue by Adminbnc** [ToniMacaroni/SaberFactory#41]
so when you set the trail length and width on 0 it will throw critical errors in the log making the log 300K lines long.
I'm guessing its because the calculation of the value is 1 / value? (in this case 0)
```
[CRITICAL @ 12:48:42 | UnityEngine] DivideByZeroException: Attempted to divide by zero.
[CRITICAL @ 12:48:42 | UnityEngine] TrailElementCollection.MoveTailToHead () (at <95802429957344f68e874c5b2a6a4dc4>:0)
[CRITICAL @ 12:48:42 | UnityEngine] SaberFactory.Instances.Trail.SFTrail.LateUpdate () (at <71189b394f684dc39e177faad3ccf300>:0)
```

**Comment by SteffoSpieler** [comment]
I have the same issue. (#33) - To fix this right now you need to use other sabers. :/

**Comment by ToniMacaroni** [comment]
Try downloading the newest version
