### ISSUE TITLE
Certain Trails aren't working

### ISSUE THREAD

**Issue by Pqutine** [ToniMacaroni/SaberFactory#46]
There is certain Trails that I am having issues with like the colour on the trail is wrong or the trails menu just black screen when I try to fix it. Also the trail colour is glitched and won't save when I go into a song it just goes back to what it was before(which is the standard blue for both controllers). This is quite infuriating as sometimes even the right trail reverts to the standard trail but longer and the left one is completely fine.

**Comment by revanmj** [comment]
For me only those have trails on 2.3.0 and BeatSaber 1.16.1: https://modelsaber.com/Sabers/?id=1604694957&pc

All below don't have any trails (had before 1.16.x and subsequent SaberFactory update):
- https://modelsaber.com/Sabers/?id=1552207591&pc
- https://modelsaber.com/Sabers/?id=1547844713&pc
- https://modelsaber.com/Sabers/?id=1565145558&pc

**Comment by ToniMacaroni** [comment]
I will look into it

**Comment by revanmj** [comment]
SpaceOpera (https://modelsaber.com/Sabers/?id=1552207591&pc) now has trails on 2.3.1, but on red/blue levels trail is always red for both sabers (should be red for one, blue for the other).

**Comment by ToniMacaroni** [comment]
in the "Beat Saber/UserData/Saber Factory" directory you will find a TrailConfig.json file.
Change "OnlyUseVertexColor" to false in there.

**Comment by revanmj** [comment]
Thanks, with this config change it finally works like before :)
