### ISSUE TITLE
Suggestion: Make Saber-Button above modifiers optional

### ISSUE THREAD

**Issue by Vogeluff** [ToniMacaroni/SaberFactory#48]
hey it would be great if the sabers button above the modifiers could be optional.

just make it a toggle in the options. as of right now my menu there is kinda crowded and i dont switch sabers often anyways. great addition for some, but just giving the choice for it and it would be perfect!

**Comment by ToniMacaroni** [comment]
Will add in the next version

**Comment by Vogeluff** [comment]
awesome thank you! another option would to do it like technicolor and
chroma do it: have a subpoint called "mods" and put it in there. i dont
know maybe you can just integrate it into that technicolor/chroma folder
haha

wish you a great week :)

Julian Kittel ***@***.***> schrieb am So., 6. Juni 2021,
15:31:

**Comment by ToniMacaroni** [comment]
Download this artifact: https://github.com/ToniMacaroni/SaberFactory/actions/runs/941014378
Open and close Beat Saber one time to generate the config.
Go to "Beat Saber/UserData/Saber Factory.json" and set "ShowGameplaySettingsButton" to false.
