### ISSUE TITLE
Game crashes when trying to change game settings with SaberFactory installed (latest version from #pc-mods posted on 22nd January)

### ISSUE THREAD

**Issue by Nytra** [ToniMacaroni/SaberFactory#5]
Example situation: I try to change my room adjust settings. Game will crash when pressing apply.

Attached relevant log file: https://pastebin.com/r3au8xAD

Extracted crash messages from log file:

[CRITICAL @ 10:57:42 | UnityEngine] InvalidOperationException: SetStore can only be called once
[CRITICAL @ 10:57:42 | UnityEngine] IPA.Config.Config.SetStore (IPA.Config.IConfigStore store) (at <d12585421ee34a08aa460b0265362502>:0)
[CRITICAL @ 10:57:42 | UnityEngine] IPA.Config.Stores.GeneratedStore.Generated[T] (IPA.Config.Config cfg, System.Boolean loadSync) (at <d12585421ee34a08aa460b0265362502>:0)
[CRITICAL @ 10:57:42 | UnityEngine] SaberFactory.Installers.AppInstaller.InstallBindings () (at <abf7a675317841198dcd0f0a2e9133e1>:0)
[CRITICAL @ 10:57:42 | UnityEngine] Zenject.Context.InstallInstallers (System.Collections.Generic.List`1[T] normalInstallers, System.Collections.Generic.List`1[T] normalInstallerTypes, System.Collections.Generic.List`1[T] scriptableObjectInstallers, System.Collections.Generic.List`1[T] installers, System.Collections.Generic.List`1[T] installerPrefabs) (at <f809e9c03b0345b2ba51b550f696ea1a>:0)
[CRITICAL @ 10:57:42 | UnityEngine] (wrapper dynamic-method) Zenject.Context.Zenject.Context.InstallInstallers_Patch1(Zenject.Context)
[CRITICAL @ 10:57:42 | UnityEngine] Zenject.SceneContext.InstallBindings (System.Collections.Generic.List`1[T] injectableMonoBehaviours) (at <f809e9c03b0345b2ba51b550f696ea1a>:0)
[CRITICAL @ 10:57:42 | UnityEngine] Zenject.SceneContext.Install () (at <f809e9c03b0345b2ba51b550f696ea1a>:0)
[CRITICAL @ 10:57:42 | UnityEngine] Zenject.SceneContext.RunInternal () (at <f809e9c03b0345b2ba51b550f696ea1a>:0)
[CRITICAL @ 10:57:42 | UnityEngine] Zenject.RunnableContext.Run () (at <f809e9c03b0345b2ba51b550f696ea1a>:0)
[CRITICAL @ 10:57:42 | UnityEngine] Zenject.RunnableContext.Initialize () (at <f809e9c03b0345b2ba51b550f696ea1a>:0)
[CRITICAL @ 10:57:42 | UnityEngine] Zenject.SceneContext.Awake () (at <f809e9c03b0345b2ba51b550f696ea1a>:0)
[CRITICAL @ 10:57:42 | UnityEngine] NullReferenceException: Object reference not set to an instance of an object
[CRITICAL @ 10:57:42 | UnityEngine] MarkSceneAsPersistent.Awake () (at <d70da00dfa9f435d9f2597dfb669d3df>:0)
[CRITICAL @ 10:57:42 | UnityEngine] NullReferenceException: Object reference not set to an instance of an object
[CRITICAL @ 10:57:42 | UnityEngine] AppInit.Start () (at <0c396efd180746249653ab114cef2375>:0)

**Comment by ToniMacaroni** [comment]
I will push a fix in a minute

**Comment by ToniMacaroni** [comment]
#7 
version 2.0.1 should fix it

**Comment by Nytra** [comment]
ty!
